### ISSUE TITLE
Gradle sync failed: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by thintin** [LinkedInLearning/androiddev-esst-2835051#1]
## Issue Overview

I'm following the Android Essential Training video and have run into a problem that I can't find an online solution for. I connected to the github repository and opened the project but I get the following error: Gradle sync failed: SSL peer shut down incorrectly 
## Describe your environment

Windows 11 Pro 21H2 running on Dell Inspiron 7506 2n1 (11th gen i7 2.8ghz CPU, 16GB RAM) Android Studio Bumblebee 2021.1.1 patch 2.
## Steps to Reproduce

1. Connect to github via Android Studio
2. Open project
3.
4.

## Expected Behavior

Gradle to complete
## Current Behavior

Gradle sync failed: SSL peer shut down incorrectly

**Comment by thintin** [comment]
Found the problem, my build gradle was set to a different version than my IDE. Changed ext.Kotlin_version to match, and hey presto!

**Comment by dannyholyoake** [comment]
> Found the problem, my build gradle was set to a different version than my IDE. Changed ext.Kotlin_version to match, and hey presto!

I'm experiencing this issue. How'd you find out what ext.kotlin_version _should_ be? Android Studio suggests my Kotlin version is 1.7.0, but putting that into ext.Kotlin_version generates more errors for me.
